<a href="https://colab.research.google.com/github/Rogerio-mack/game_q/blob/main/geq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
df = pd.read_excel('https://github.com/Rogerio-mack/game_q/raw/refs/heads/main/Pos_Jogo.xlsx', skiprows=1, header=0)

display(df.head())


Unnamed: 0          Carimbo de data/hora                       Email:  \
0           1  2024/10/29 11:18:06 AM GMT-3  10418084@mackenzista.com.br   
1           2  2024/10/29 12:03:32 PM GMT-3      tito.guidotti@gmail.com   
2           3   2024/11/04 7:50:18 AM GMT-3  10418316@mackenzista.com.br   
3           4   2024/11/04 7:50:56 AM GMT-3      luiza.kawkami@yahoo.com   
4           5   2024/11/04 7:52:33 AM GMT-3  10418105@mackenzista.com.br   

  Eu me senti revigorado   Eu me senti mal Achei difícil voltar à realidade  \
0      moderadamente (2)          nada (0)                         nada (0)   
1      moderadamente (2)          nada (0)                         nada (0)   
2       ligeiramente (1)          nada (0)                         nada (0)   
3               nada (0)  ligeiramente (1)                         nada (0)   
4      moderadamente (2)          nada (0)                         nada (0)   

  Eu me senti culpado. Foi como uma vitória Achei uma perda de tempo  \
0             nada (0)             nada (0)         ligeiramente (1)   
1             nada (0)         bastante (3)                 nada (0)   
2             nada (0)     ligeiramente (1)                 nada (0)   
3             nada (0)             nada (0)         ligeiramente (1)   
4             nada (0)    moderadamente (2)                 nada (0)   

  Eu me senti energizado  ... Eu me senti desorientado Eu me senti exausto  \
0      moderadamente (2)  ...             bastante (3)   moderadamente (2)   
1      moderadamente (2)  ...        moderadamente (2)   moderadamente (2)   
2      moderadamente (2)  ...                 nada (0)            nada (0)   
3               nada (0)  ...        moderadamente (2)            nada (0)   
4           bastante (3)  ...                 nada (0)            nada (0)   

  Senti que poderia ter feito coisas mais úteis Eu me senti poderoso  \
0                             moderadamente (2)             nada (0)   
1                             moderadamente (2)    moderadamente (2)   
2                              ligeiramente (1)             nada (0)   
3                                      nada (0)             nada (0)   
4                                      nada (0)     ligeiramente (1)   

  Eu me senti esgotado     Senti remorso Eu me senti envergonhado  \
0     ligeiramente (1)  ligeiramente (1)                 nada (0)   
1             nada (0)          nada (0)                 nada (0)   
2             nada (0)          nada (0)                 nada (0)   
3             nada (0)          nada (0)                 nada (0)   
4             nada (0)          nada (0)                 nada (0)   

  Eu me senti orgulhoso Tive a sensação de ter voltado de uma viagem  \
0     moderadamente (2)                                     nada (0)   
1          bastante (3)                                     nada (0)   
2      ligeiramente (1)                                     nada (0)   
3              nada (0)                                     nada (0)   
4          bastante (3)                                     nada (0)   

  Você ficou com alguma dúvida com alguma questão deste questionário?  
0                                                Não                   
1                                                Não                   
2                                                Não                   
3                                                Não                   
4                                                Não                   

[5 rows x 21 columns]

In [3]:
df.drop(columns=['Unnamed: 0','Carimbo de data/hora', 'Email:'], inplace=True)
questions = df.columns.to_list()
display(questions)
df.columns = [f'Q{i+1}' for i in range(0,df.shape[1])]
display(df.head())

['Eu me senti revigorado',
 'Eu me senti mal',
 'Achei difícil voltar à realidade',
 'Eu me senti culpado.',
 'Foi como uma vitória',
 'Achei uma perda de tempo',
 'Eu me senti energizado',
 'Eu me senti satisfeito',
 'Eu me senti desorientado',
 'Eu me senti exausto',
 'Senti que poderia ter feito coisas mais úteis',
 'Eu me senti poderoso',
 'Eu me senti esgotado',
 'Senti remorso',
 'Eu me senti envergonhado',
 'Eu me senti orgulhoso',
 'Tive a sensação de ter voltado de uma viagem',
 'Você ficou com alguma dúvida com alguma questão deste questionário?']

Q1                Q2        Q3        Q4                 Q5  \
0  moderadamente (2)          nada (0)  nada (0)  nada (0)           nada (0)   
1  moderadamente (2)          nada (0)  nada (0)  nada (0)       bastante (3)   
2   ligeiramente (1)          nada (0)  nada (0)  nada (0)   ligeiramente (1)   
3           nada (0)  ligeiramente (1)  nada (0)  nada (0)           nada (0)   
4  moderadamente (2)          nada (0)  nada (0)  nada (0)  moderadamente (2)   

                 Q6                 Q7                 Q8                 Q9  \
0  ligeiramente (1)  moderadamente (2)  moderadamente (2)       bastante (3)   
1          nada (0)  moderadamente (2)  moderadamente (2)  moderadamente (2)   
2          nada (0)  moderadamente (2)  moderadamente (2)           nada (0)   
3  ligeiramente (1)           nada (0)           nada (0)  moderadamente (2)   
4          nada (0)       bastante (3)   extremamente (4)           nada (0)   

                 Q10                Q11                Q12               Q13  \
0  moderadamente (2)  moderadamente (2)           nada (0)  ligeiramente (1)   
1  moderadamente (2)  moderadamente (2)  moderadamente (2)          nada (0)   
2           nada (0)   ligeiramente (1)           nada (0)          nada (0)   
3           nada (0)           nada (0)           nada (0)          nada (0)   
4           nada (0)           nada (0)   ligeiramente (1)          nada (0)   

                Q14       Q15                Q16       Q17  Q18  
0  ligeiramente (1)  nada (0)  moderadamente (2)  nada (0)  Não  
1          nada (0)  nada (0)       bastante (3)  nada (0)  Não  
2          nada (0)  nada (0)   ligeiramente (1)  nada (0)  Não  
3          nada (0)  nada (0)           nada (0)  nada (0)  Não  
4          nada (0)  nada (0)       bastante (3)  nada (0)  Não

In [4]:
df.Q1.value_counts()

Q1
moderadamente (2)    47
ligeiramente (1)     24
nada (0)             21
bastante (3)         17
extremamente (4)      6
Name: count, dtype: int64

In [5]:
df.drop(columns=['Q18'], inplace=True)

replace_map = {
    'moderadamente (2)': 2,
    'ligeiramente (1)': 1,
    'nada (0)': 0,
    'bastante (3)': 3,
    'extremamente (4)': 4
}

pd.set_option('future.no_silent_downcasting', True)
df = df.replace(replace_map)
print(df.head())

  Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10 Q11 Q12 Q13 Q14 Q15 Q16 Q17
0  2  0  0  0  0  1  2  2  3   2   2   0   1   1   0   2   0
1  2  0  0  0  3  0  2  2  2   2   2   2   0   0   0   3   0
2  1  0  0  0  1  0  2  2  0   0   1   0   0   0   0   1   0
3  0  1  0  0  0  1  0  0  2   0   0   0   0   0   0   0   0
4  2  0  0  0  2  0  3  4  0   0   0   1   0   0   0   3   0


In [6]:
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Criar e ajustar o modelo PCA
pca = PCA(n_components=3)  # Manter todos os 10 componentes
pca.fit(df)

# Cálculo das cargas fatoriais
loads = pca.components_.T * np.sqrt(pca.explained_variance_)

# Criar um DataFrame para as cargas fatoriais
factor_loadings = pd.DataFrame(loads, index=df.columns, columns=[f'Componente_{i+1}' for i in range(loads.shape[1])])

# Exibir as cargas fatoriais
print("Cargas Fatoriais:")
print(factor_loadings)

# Opcional: Plotar as cargas fatoriais
plt.figure(figsize=(10, 6))
plt.matshow(factor_loadings, fignum=1, cmap='viridis')
plt.colorbar()
plt.title('Cargas Fatoriais')
plt.xticks(ticks=np.arange(factor_loadings.shape[1]), labels=factor_loadings.columns)
plt.yticks(ticks=np.arange(factor_loadings.shape[0]), labels=factor_loadings.index)
plt.show()

Cargas Fatoriais:
     Componente_1  Componente_2  Componente_3
Q1       0.872362     -0.091041      0.133053
Q2      -0.086302      0.564104     -0.079418
Q3       0.237080      0.283057      0.064089
Q4       0.158765      0.443116      0.055940
Q5       1.035297     -0.059087      0.333048
Q6      -0.150491      0.567829      0.154966
Q7       0.909492      0.023505      0.070106
Q8       0.879677     -0.367866      0.369565
Q9      -0.066300      0.679673     -0.086896
Q10      0.046007      0.536219     -0.110934
Q11     -0.068259      0.719510      0.771069
Q12      0.945272      0.133724     -0.214135
Q13      0.013696      0.440963     -0.142522
Q14      0.145181      0.429639     -0.052405
Q15     -0.041479      0.382871     -0.063752
Q16      1.058215     -0.003366     -0.052987
Q17      0.908944      0.367047     -0.594056


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<Figure size 1000x600 with 0 Axes>

In [7]:
!pip install factor_analyzer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for factor_analyzer: filename=factor_analyzer-0.5.1-py2.py3-none-any.whl size=42621 sha256=3e46637aaad4af78cf3d845aaa455cc4d3204eb571c2bb14ef23e36945417018
  Stored in directory: /root/.cache/pip/wheels/fa/f7/53/a55a8a56668a6fe0199e0e02b6e0ae3007ec35cdf6e4c25df7
Successfully built factor_analyzer


In [25]:
import pandas as pd
import numpy as np
from factor_analyzer import FactorAnalyzer
import matplotlib.pyplot as plt

# Criar e ajustar o modelo de análise fatorial
fa = FactorAnalyzer(n_factors=3, rotation='varimax')
fa.fit(df)

# Extraindo cargas fatoriais
factor_loadings = fa.loadings_

fa = FactorAnalyzer(n_factors=3, rotation='oblimin')
fa.fit(df)
structure_matrix = fa.structure_

# Criar DataFrames para as cargas fatoriais e matriz de estrutura
loadings_df = pd.DataFrame(factor_loadings, index=df.columns, columns=[f'Fator_{i+1}' for i in range(factor_loadings.shape[1])])
structure_df = pd.DataFrame(structure_matrix, index=df.columns, columns=[f'Fator_{i+1}' for i in range(structure_matrix.shape[1])])

# Exibir as cargas fatoriais e a matriz de estrutura
print("Matriz de Cargas Fatoriais:")
print(loadings_df)
print("\nMatriz de Estrutura:")
print(structure_df)

fa = FactorAnalyzer(n_factors=3, rotation=None)
fa.fit(df)
# Exibir Matriz-Padrão (caracteriza a relação entre fatores e variáveis)
standardized_loadings = fa.standardized_loadings_
standardized_loadings_df = pd.DataFrame(standardized_loadings, index=df.columns, columns=[f'Fator_{i+1}' for i in range(standardized_loadings.shape[1])])
print("\nMatriz-Padrão:")
print(standardized_loadings_df)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Matriz de Cargas Fatoriais:
      Fator_1   Fator_2   Fator_3
Q1   0.792480 -0.058012 -0.015909
Q2  -0.113415  0.603744  0.307148
Q3   0.327130  0.520013 -0.008767
Q4   0.208506  0.573653  0.145656
Q5   0.731555  0.075942 -0.135713
Q6  -0.202016  0.581955  0.306639
Q7   0.746658 -0.068195  0.173427
Q8   0.727959 -0.201084 -0.163484
Q9  -0.069174  0.448762  0.494957
Q10  0.074900  0.198789  0.877337
Q11 -0.066538  0.406996  0.140407
Q12  0.683829  0.127072 -0.014511
Q13  0.018133  0.308530  0.655121
Q14  0.177062  0.757450 -0.000199
Q15 -0.090375  0.529993  0.294504
Q16  0.812241 -0.015131  0.015304
Q17  0.607077  0.212012  0.073728

Matriz de Estrutura:
      Fator_1   Fator_2   Fator_3
Q1   0.794324  0.028406 -0.024726
Q2  -0.154406  0.618993  0.460196
Q3   0.302197  0.548426  0.137058
Q4   0.174932  0.606148  0.299296
Q5   0.732082  0.140041 -0.103634
Q6  -0.241778  0.587643  0.452997
Q7   0.741311  0.035207  0.154151
Q8   0.742763 -0.137029 -0.206442
Q9  -0.110607  0.492630  0.59858

AttributeError: 'FactorAnalyzer' object has no attribute 'standardized_loadings_'

In [26]:
fa = FactorAnalyzer(n_factors=3, rotation='varimax')
fa.fit(df)

fa.get_communalities()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


array([0.63164308, 0.47170929, 0.37750407, 0.39376813, 0.55935808,
       0.47350997, 0.59222609, 0.59708616, 0.45115518, 0.81484753,
       0.18978686, 0.48398013, 0.52470273, 0.60508143, 0.37579288,
       0.66019786, 0.41892745])

In [22]:
# Criar e ajustar o modelo de análise fatorial
fa = FactorAnalyzer(n_factors=3, rotation='varimax')
fa.fit(df)

# Extraindo cargas fatoriais
factor_loadings = fa.loadings_
display(factor_loadings)

loadings_df = pd.DataFrame(factor_loadings, index=df.columns, columns=[f'Fator_{i+1}' for i in range(factor_loadings.shape[1])])
# display(loadings_df)
display(fa.get_communalities())
display(fa.get_communalities().mean())

fa = FactorAnalyzer(n_factors=3, rotation='oblimin')
fa.fit(df)

fa.structure_




/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


array([[ 0.79432407,  0.02840575, -0.02472609],
       [-0.15440564,  0.61899348,  0.46019567],
       [ 0.30219715,  0.54842576,  0.13705827],
       [ 0.17493181,  0.6061483 ,  0.2992958 ],
       [ 0.73208238,  0.14004066, -0.10363437],
       [-0.24177816,  0.58764281,  0.4529966 ],
       [ 0.74131079,  0.03520676,  0.15415119],
       [ 0.74276348, -0.13702882, -0.20644193],
       [-0.1106066 ,  0.49262985,  0.59858064],
       [ 0.02935161,  0.3060415 ,  0.89878144],
       [-0.09145726,  0.41065722,  0.24622535],
       [ 0.67705636,  0.19926976,  0.02655306],
       [-0.0233919 ,  0.3823819 ,  0.71478701],
       [ 0.14081888,  0.7672252 ,  0.20926925],
       [-0.12739602,  0.5472733 ,  0.4279748 ],
       [ 0.81073318,  0.07652872,  0.01722311],
       [ 0.59281056,  0.28485292,  0.13409257]])

In [32]:
pca = PCA(n_components=3)  # Número de componentes a serem retidos
pca.fit(df)

# Cálculo das cargas fatoriais
factor_loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
display(factor_loadings)
display(pca.explained_variance_)

# Cálculo das comunalidades
communalities = np.sum(factor_loadings**2, axis=1)

# Criar DataFrame para as comunalidades
comunalities_df = pd.DataFrame(communalities, index=df.columns, columns=['Comunalidade'])

# Exibir as comunalidades
print("Comunalidades:")
print(comunalities_df)

array([[ 0.87236247, -0.09104139,  0.1330529 ],
       [-0.0863018 ,  0.56410441, -0.07941763],
       [ 0.23708016,  0.28305666,  0.06408934],
       [ 0.15876539,  0.44311571,  0.05593958],
       [ 1.03529656, -0.05908679,  0.3330478 ],
       [-0.15049089,  0.56782932,  0.15496606],
       [ 0.90949167,  0.02350499,  0.07010639],
       [ 0.87967704, -0.36786623,  0.36956497],
       [-0.06630011,  0.6796731 , -0.08689612],
       [ 0.0460068 ,  0.53621923, -0.11093396],
       [-0.06825873,  0.7195097 ,  0.77106906],
       [ 0.9452715 ,  0.13372436, -0.21413502],
       [ 0.0136959 ,  0.44096291, -0.14252182],
       [ 0.14518078,  0.42963885, -0.05240508],
       [-0.04147916,  0.38287101, -0.06375221],
       [ 1.05821544, -0.00336591, -0.05298705],
       [ 0.90894352,  0.36704715, -0.59405578]])

array([6.4190646 , 3.01020035, 1.35076699])

Comunalidades:
     Comunalidade
Q1       0.787008
Q2       0.331969
Q3       0.140436
Q4       0.224687
Q5       1.186251
Q6       0.369092
Q7       0.832642
Q8       1.045736
Q9       0.473902
Q10      0.301954
Q11      1.116901
Q12      0.957274
Q13      0.214948
Q14      0.208413
Q15      0.152375
Q16      1.122639
Q17      1.313804


In [33]:
!pip install pingouin

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.4/204.4 kB 5.1 MB/s eta 0:00:00


In [41]:
for c in df:
  df[c] = df[c].astype(int)

In [40]:
df.dtypes

Q1     float64
Q2     float64
Q3     float64
Q4     float64
Q5     float64
Q6     float64
Q7     float64
Q8     float64
Q9     float64
Q10    float64
Q11    float64
Q12    float64
Q13    float64
Q14    float64
Q15    float64
Q16    float64
Q17    float64
dtype: object

In [42]:
import pingouin as pg

# Calcular o alfa de Cronbach
cronbach_alpha = pg.cronbach_alpha(df)


TypeError: tuple indices must be integers or slices, not str

In [43]:
cronbach_alpha

(0.8073800001257697, array([0.752, 0.855]))

Valores próximos de 1 indicam alta consistência interna entre os itens do teste.
Valores abaixo de 0.7 podem sugerir problemas de confiabilidade (dependendo do contexto, valores entre 0.7 e 0.9 são geralmente considerados aceitáveis).

In [45]:
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo
# from factor_analyzer import bartlett_sphericity

# Cálculo do valor de KMO
kmo_all, kmo_model = calculate_kmo(df)

# Exibir o valor de KMO
print(f'KMO: {kmo_model:.4f}')

# Cálculo do p-valor do teste de esfericidade de Bartlett
# chi2, p_value = bartlett_sphericity(df)

# Exibir o p-valor do teste de Bartlett
# print(f'P-valor do teste de Bartlett: {p_value:.4f}')

KMO: 0.7710


In [53]:
from scipy import stats
test_statistic, p_value = stats.bartlett(df.Q1,df.Q2,df.Q3,df.Q4,df.Q5,df.Q6,df.Q7,df.Q8,df.Q9,df.Q10,
                                         df.Q11,df.Q12,df.Q13,df.Q14,df.Q15,df.Q16,df.Q17)


print(test_statistic, p_value)

222.52422946930702 2.1351329269465187e-38


https://bookdown.org/chua/new_rasch_demo2/viewdifficulty.html#person-fit-statistics

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Substitua por seus dados de resíduos do seu modelo Rasch!
residuals = np.random.randn(40, 10) # 40 pessoas, 10 questões

# Aplique o PCA
pca = PCA()
pca.fit(residuals)

# Autovalores
eigenvalues = pca.explained_variance_

# Variância Explicada
explained_variance_ratio = pca.explained_variance_ratio_

# Visualizando os autovalores
plt.plot(range(1, len(eigenvalues) + 1), eigenvalues, marker='o')
plt.xlabel('Componentes Principais')
plt.ylabel('Autovalores')
plt.title('Scree Plot')
plt.show()

print("Variância Explicada por Componente:", explained_variance_ratio)